### ISSUE TITLE
OR in From

### ISSUE THREAD

**Issue by rufinus** [lyrixx/SFLive-Paris2016-Workflow#3]
Hi,

is it not possible to have an `OR` in from of the transistion?

for example:

```
        client:
            marking_store:
                type: property_accessor
                arguments:
                    - state
            supports:
                - AppBundle\Model\Entity\Client
            places:
                - new
                - active
                - inactive
                - suspended
            transitions:
                activate:
                    from: [new, inactive, suspended]
                    to: active
                deactivate:
                    from: [new, active]
                    to: inactive
                suspend:
                    from: active
                    to: suspended
```

As it stands now, it cant work, as the marking has to be new, inactive and suspended to be activated.

How would i have multiple from as or without having multiple transistions i have to check/call?
